import {loadLocale,t,applyTranslations,registerTranslations} from "./i18n.js";
import {ResourceRegistry} from "./core/resource-registry.js";
import {AssetRegistry} from "./core/asset-registry.js";
import {CatalogRegistry} from "./core/catalog-registry.js";
import {createModAPI} from "./modding/mod-api.js";
import {loadMods} from "./modding/mod-loader.js";
const state={scene:"desk",minutes:19*60+30};let resources,assets,catalog,sceneData,modAPI;
const env=document.querySelector("#environment"),hotspotLayer=document.querySelector("#hotspotLayer"),back=document.querySelector("#backButton"),toast=document.querySelector("#toast"),rainFx=document.querySelector("#rainFx"),darknessFx=document.querySelector("#darknessFx");
function timeString(){const h=Math.floor(state.minutes/60)%24,m=state.minutes%60;return `${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}`}
function passTime(m){state.minutes=(state.minutes+m)%(24*60)}
function renderHUD(){document.querySelector("#money").textContent=`${resources.get("money")} EUR`;document.querySelector("#income").textContent=`${resources.get("income")} EUR`;document.querySelector("#expenses").textContent=`${resources.get("expenses")} EUR`;document.querySelector("#clock").textContent=timeString();for(const id of ["energy","focus","health"]){const v=resources.get(id);document.querySelector(`#${id}`).textContent=v;document.querySelector(`#${id}Bar`).style.width=`${v}%`}const late=Math.max(0,(state.minutes-21*60)/240),tired=(100-resources.get("energy"))/100;darknessFx.style.opacity=String(Math.min(.5,late*.18+tired*.12))}
function showToast(text){toast.textContent=text;toast.classList.add("show");clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>toast.classList.remove("show"),1900)}
function addAssetVisual(host,ref,label){if(!ref)return;if(typeof ref==="string"){const img=document.createElement("img");img.src=ref;img.alt=label;host.appendChild(img);return}if(ref.atlas&&ref.crop){const [x,y,w,h]=ref.crop,[aw,ah]=ref.atlas_size;const clip=document.createElement("span");clip.className="atlas-clip";clip.style.aspectRatio=`${w}/${h}`;const img=document.createElement("img");img.src=ref.atlas;img.alt=label;img.style.width=`${aw/w*100}%`;img.style.left=`${-x/w*100}%`;img.style.top=`${-y/w*100}%`;clip.appendChild(img);host.appendChild(clip)}}
function createHotspot(h){const b=document.createElement("button");b.className="hotspot";b.dataset.action=h.action;b.style.left=`${h.x}%`;b.style.top=`${h.y}%`;b.style.width=`${h.w}%`;addAssetVisual(b,assets.resolve(h.asset_id,h.variant||"icon"),t(h.label_key,h.id));const tip=document.createElement("span");tip.className="tip";tip.textContent=[t(h.label_key,h.id),h.hint_key?t(h.hint_key,""):""].filter(Boolean).join(" - ");b.appendChild(tip);return b}
function renderScene(){const scene=sceneData.scenes[state.scene];env.src=assets.resolve(scene.environment_asset,"world")||"";hotspotLayer.replaceChildren(...scene.hotspots.map(createHotspot));back.style.display=state.scene==="desk"?"none":"block";rainFx.style.display=state.scene==="desk"?"block":"none";renderHUD();modAPI?.events.emit("scene:changed",{scene:state.scene})}
function useItem(id){const item=catalog.get(id);if(!item)return;const effects=item.effects||{};if(effects.time_minutes)passTime(effects.time_minutes);for(const [res,delta] of Object.entries(effects)){if(res!=="time_minutes"&&resources.getDefinition(res))resources.add(res,delta,`item:${id}`)}}
function action(name){switch(name){case"coffee":useItem("coffee_starter_white");showToast(t("toast.coffee"));break;case"phone":showToast(t("toast.phone_placeholder"));break;case"notebook":showToast(t("toast.notebook_placeholder"));break;case"map":state.scene="map";break;case"storage":state.scene="storage";break;case"desk":state.scene="desk";break;case"vehicle":showToast(t("toast.vehicle"));break;case"client":showToast(t("toast.client_placeholder"));break;case"hardware":showToast(t("toast.hardware_placeholder"));break;case"inspect_vacuum":showToast(t("toast.vacuum"));break;case"inspect_caddy":showToast(t("toast.caddy"));break}modAPI?.events.emit("action",{name,scene:state.scene});renderScene()}
document.addEventListener("click",e=>{const el=e.target.closest("[data-action]");if(el)action(el.dataset.action)});
async function bootstrap(){await loadLocale("de");applyTranslations();document.title=t("app.title","Founder Sim");[resources,assets,catalog,sceneData]=await Promise.all([ResourceRegistry.fromUrl("data/resources.json"),AssetRegistry.fromUrl("assets/manifest.json"),CatalogRegistry.fromUrl("data/catalog/items.json"),fetch("data/scenes.json").then(r=>r.json())]);modAPI=createModAPI({resources,assets,catalog,i18n:{t,registerTranslations,applyTranslations}});window.FounderSimModAPI=modAPI;await loadMods(modAPI,registerTranslations);applyTranslations();resources.subscribe(renderHUD);renderScene()}
bootstrap().catch(err=>{console.error(err);showToast(`${t("errors.startup_prefix","Startfehler")}: ${err.message}`)});
